version: '3.8'
services:
  dev-database:
    image: postgres:15.0
    container_name: dev-database
    ports:
      - "5434:5432"  # Thêm dấu gạch ngang ở đây
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abc123456789
      POSTGRES_DB: testdb
    networks:
      - nestjs-networks

  test-database:
    image: postgres:15.0
    container_name: test-database
    ports:
      - "5435:5432"  # Thêm dấu gạch ngang ở đây
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abc123456789
      POSTGRES_DB: testdb
    networks:
      - nestjs-networks
networks:
  nestjs-networks:


#-d: detach mode Tạo ra
# docker compose up -d


# Xóa
# docker compose rm (name) --stop --force  --volumes